name: Planetary Data Management of Small Archives
description: TWSC training for planetary scientists and data managers to create federally-compliant archives outside of the PDS
url: "https://mahunterusgs.github.io/TWSC_Data_Management/"
markdown: GFM
highlighter: rouge
